import type {
  Background,
  CharacterClass,
  EquipmentPreset,
  Race,
  Skill,
  Spell,
} from './types';

// Import existing class images
import BarbarianFemaleImage from '../pages/create/ui/class-selection-form/assets/barbarian-female.webp';
import BarbarianMaleImage from '../pages/create/ui/class-selection-form/assets/barbarian-male.webp';
import BardFemaleImage from '../pages/create/ui/class-selection-form/assets/bard-female.webp';
import BardMaleImage from '../pages/create/ui/class-selection-form/assets/bard-male.webp';
import ClericFemaleImage from '../pages/create/ui/class-selection-form/assets/cleric-female.webp';
import ClericMaleImage from '../pages/create/ui/class-selection-form/assets/cleric-male.webp';
import DruidFemaleImage from '../pages/create/ui/class-selection-form/assets/druid-female.webp';
import DruidMaleImage from '../pages/create/ui/class-selection-form/assets/druid-male.webp';
import FighterFemaleImage from '../pages/create/ui/class-selection-form/assets/fighter-female.webp';
import FighterMaleImage from '../pages/create/ui/class-selection-form/assets/fighter-male.webp';

export const CHARACTER_CLASSES: CharacterClass[] = [
  {
    id: 'barbarian',
    name: 'Barbarian',
    description: 'Unleash primal fury. Channel rage into unstoppable devastation.',
    images: {
      male: BarbarianMaleImage,
      female: BarbarianFemaleImage,
    },
    keyTraits: ['Rage', 'Unarmored Defense'],
    hitDie: 'd12',
    primaryAbility: 'Strength',
    combatType: 'Melee',
    isCaster: false,
    skillCount: 2,
    skillOptions: [
      'animal-handling',
      'athletics',
      'intimidation',
      'nature',
      'perception',
      'survival',
    ],
  },
  {
    id: 'bard',
    name: 'Bard',
    description: 'Weave magic through music. Inspire allies, deceive foes.',
    images: {
      male: BardMaleImage,
      female: BardFemaleImage,
    },
    keyTraits: ['Jack of All Trades', 'Bardic Inspiration'],
    hitDie: 'd8',
    primaryAbility: 'Charisma',
    combatType: 'Magic',
    isCaster: true,
    skillCount: 3,
    skillOptions: [
      'acrobatics',
      'animal-handling',
      'arcana',
      'athletics',
      'deception',
      'history',
      'insight',
      'intimidation',
      'investigation',
      'medicine',
      'nature',
      'perception',
      'performance',
      'persuasion',
      'religion',
      'sleight-of-hand',
      'stealth',
      'survival',
    ],
  },
  {
    id: 'cleric',
    name: 'Cleric',
    description: 'Wield divine power. Heal the wounded, smite the unholy.',
    images: {
      male: ClericMaleImage,
      female: ClericFemaleImage,
    },
    keyTraits: ['Divine Magic', 'Channel Divinity'],
    hitDie: 'd8',
    primaryAbility: 'Wisdom',
    combatType: 'Magic',
    isCaster: true,
    skillCount: 2,
    skillOptions: ['history', 'insight', 'medicine', 'persuasion', 'religion'],
  },
  {
    id: 'druid',
    name: 'Druid',
    description: 'Command nature itself. Shapeshift into beasts at will.',
    images: {
      male: DruidMaleImage,
      female: DruidFemaleImage,
    },
    keyTraits: ['Wild Shape', 'Nature Magic'],
    hitDie: 'd8',
    primaryAbility: 'Wisdom',
    combatType: 'Hybrid',
    isCaster: true,
    skillCount: 2,
    skillOptions: [
      'arcana',
      'animal-handling',
      'insight',
      'medicine',
      'nature',
      'perception',
      'religion',
      'survival',
    ],
  },
  {
    id: 'fighter',
    name: 'Fighter',
    description: 'Master every weapon. Dominate the battlefield with skill.',
    images: {
      male: FighterMaleImage,
      female: FighterFemaleImage,
    },
    keyTraits: ['Action Surge', 'Extra Attack'],
    hitDie: 'd10',
    primaryAbility: 'Strength',
    combatType: 'Melee',
    isCaster: false,
    skillCount: 2,
    skillOptions: [
      'acrobatics',
      'animal-handling',
      'athletics',
      'history',
      'insight',
      'intimidation',
      'perception',
      'survival',
    ],
  },
    {
    id: 'monk',
    name: 'Monk',
    description: 'Harness inner ki. Strike with speed and precision.',
    images: {
      male: FighterMaleImage,
      female: FighterMaleImage,
    },
    keyTraits: ['Martial Arts', 'Ki'],
    hitDie: 'd8',
    primaryAbility: 'Dexterity',
    combatType: 'Melee',
    isCaster: false,
    skillCount: 2,
    skillOptions: [
      'acrobatics',
      'athletics',
      'history',
      'insight',
      'religion',
      'stealth',
    ],
  },
  {
    id: 'paladin',
    name: 'Paladin',
    description: 'Swear a sacred oath. Smite evil with divine power.',
    images: {
      male: FighterMaleImage,
      female: FighterMaleImage,
    },
    keyTraits: ['Divine Smite', 'Lay on Hands'],
    hitDie: 'd10',
    primaryAbility: 'Strength',
    combatType: 'Hybrid',
    isCaster: true,
    skillCount: 2,
    skillOptions: [
      'athletics',
      'insight',
      'intimidation',
      'medicine',
      'persuasion',
      'religion',
    ],
  },
  {
    id: 'ranger',
    name: 'Ranger',
    description: 'Track your prey. Master survival and ranged combat.',
    images: {
      male: FighterMaleImage,
      female: FighterMaleImage,
    },
    keyTraits: ['Favored Enemy', 'Natural Explorer'],
    hitDie: 'd10',
    primaryAbility: 'Dexterity',
    combatType: 'Hybrid',
    isCaster: true,
    skillCount: 3,
    skillOptions: [
      'animal-handling',
      'athletics',
      'insight',
      'investigation',
      'nature',
      'perception',
      'stealth',
      'survival',
    ],
  },
  {
    id: 'rogue',
    name: 'Rogue',
    description: 'Strike from the shadows. Exploit every weakness.',
    images: {
      male: FighterMaleImage,
      female: FighterMaleImage,
    },
    keyTraits: ['Sneak Attack', 'Cunning Action'],
    hitDie: 'd8',
    primaryAbility: 'Dexterity',
    combatType: 'Melee',
    isCaster: false,
    skillCount: 4,
    skillOptions: [
      'acrobatics',
      'athletics',
      'deception',
      'insight',
      'intimidation',
      'investigation',
      'perception',
      'performance',
      'persuasion',
      'sleight-of-hand',
      'stealth',
    ],
  },
  {
    id: 'sorcerer',
    name: 'Sorcerer',
    description: 'Innate arcane power flows through your blood.',
    images: {
      male: FighterMaleImage,
      female: FighterMaleImage,
    },
    keyTraits: ['Metamagic', 'Sorcery Points'],
    hitDie: 'd6',
    primaryAbility: 'Charisma',
    combatType: 'Magic',
    isCaster: true,
    skillCount: 2,
    skillOptions: [
      'arcana',
      'deception',
      'insight',
      'intimidation',
      'persuasion',
      'religion',
    ],
  },
  {
    id: 'warlock',
    name: 'Warlock',
    description: 'Gain power through a pact with a mysterious patron.',
    images: {
      male: FighterMaleImage,
      female: FighterMaleImage,
    },
    keyTraits: ['Pact Magic', 'Eldritch Invocations'],
    hitDie: 'd8',
    primaryAbility: 'Charisma',
    combatType: 'Magic',
    isCaster: true,
    skillCount: 2,
    skillOptions: [
      'arcana',
      'deception',
      'history',
      'intimidation',
      'investigation',
      'nature',
      'religion',
    ],
  },
  {
    id: 'wizard',
    name: 'Wizard',
    description: 'Study the arcane. Shape reality through knowledge.',
    images: {
      male: FighterMaleImage,
      female: FighterMaleImage,
    },
    keyTraits: ['Spellcasting', 'Arcane Recovery'],
    hitDie: 'd6',
    primaryAbility: 'Intelligence',
    combatType: 'Magic',
    isCaster: true,
    skillCount: 2,
    skillOptions: [
      'arcana',
      'history',
      'insight',
      'investigation',
      'medicine',
      'religion',
    ],
  },

];

export const RACES: Race[] = [
  {
    id: 'human',
    name: 'Человек',
    description: 'Универсальная и адаптивная раса, способная преуспеть в любой роли.',
    image: '', // Add image path if available
    abilityBonuses: { str: 1, dex: 1, con: 1, int: 1, wis: 1, cha: 1 },
    speed: 30,
    size: 'Средний',
    traits: ['Черта', 'Увеличение характеристик'],
  },
  {
    id: 'elf',
    name: 'Эльф',
    description: 'Грациозные и долгоживущие создания с острыми чувствами и связью с магией фей.',
    image: '',
    abilityBonuses: { dex: 2 },
    speed: 30,
    size: 'Средний',
    traits: ['Тёмное зрение', 'Острое чутьё', 'Наследие фей', 'Медитация'],
    subraces: [
      {
        id: 'high-elf',
        name: 'Высший эльф',
        description: 'Утончённые и интеллектуальные эльфы, посвятившие себя изучению магии и искусств.',
        abilityBonuses: { int: 1 },
        traits: ['Заговор', 'Дополнительный язык'],
      },
      {
        id: 'wood-elf',
        name: 'Лесной эльф',
        description: 'Замкнутые защитники лесов, живущие в гармонии с природой.',
        abilityBonuses: { wis: 1 },
        traits: ['Маска дикой природы', 'скорость 35 фт'],
      },
      {
        id: 'drou',
        name: 'Дроу',
        description: 'Жители Подземья с жёсткой иерархической культурой и врождённой магией.',
        abilityBonuses: { wis: 1 },
        traits: ['Чувствительность к солнечному свету', 'Магия дроу', 'тёмное зрение 120 фт'],
      },
    ],
  },
  {
    id: 'dwarf',
    name: 'Дварф',
    description: 'Крепкие и выносливые мастера гор и кузнечного дела.',
    image: '',
    abilityBonuses: { con: 2 },
    speed: 25,
    size: 'Небольшой',
    traits: ['Тёмное зрение', 'Дварфийская стойкость', 'Знание камня'],
    subraces: [
      {
        id: 'mountain-dwarf',
        name: 'Горный дварф',
        description: 'Гордые и воинственные мастера кузнечного дела.',
        abilityBonuses: { str: 2 },
        traits: ['Владение дварфийскими доспехами'],
      },
      {
        id: 'hill-dwarf',
        name: 'Холмовой дварф',
        description: 'Более миролюбивые и стойкие дварфы, известные своей выносливостью и мудростью.',
        abilityBonuses: { wis: 1 },
        traits: ['Дварфийская выносливость'],
      },
    ],
  },
  {
    id: 'halfling',
    name: 'Полурослик',
    description: 'Маленькие, ловкие и необычайно удачливые путешественники',
    image: '',
    abilityBonuses: { dex: 2 },
    speed: 25,
    size: 'Небольшой',
    traits: ['Везучий', 'Храбрый', 'Проворство полурослика'],
    subraces: [
      {
        id: 'lightfoot',
        name: 'Лёгконогий',
        description: 'Общительные и обаятельные странники, легко находящие друзей среди других народов.',
        abilityBonuses: { cha: 1 },
        traits: ['Естественная скрытность'],
      },
      {
        id: 'stout',
        name: 'Коренастый',
        description: 'Более выносливые и устойчивые к ядам представители своего народа.',
        abilityBonuses: { con: 1 },
        traits: ['Стойкость коренастого'],
      },
    ],
  },
  {
    id: 'half-ork',
    name: 'Полуорк',
    description: 'Мощные и выносливые воины с дикой боевой яростью.',
    image: '',
    abilityBonuses: { str: 2, con: 1 },
    speed: 30,
    size: 'Средний',
    traits: ['Тёмное зрение', 'Неумолимая стойкость', 'Свирепые атаки', 'Угрожающий вид'],
  },
  {
    id: 'half-elf',
    name: 'Полуэльф',
    description: 'Сочетают человеческую адаптивность и эльфийскую грацию.',
    image: '',
    abilityBonuses: { str: 1, cha: 2 },
    speed: 30,
    size: 'Средний',
    traits: ['Тёмное зрение', 'Наследие фей', 'Универсальность навыков'],
  },
  {
    id: 'dragonborn',
    name: 'Драконорождённый',
    description: 'Потомки драконов, владеющие дыхательным оружием.',
    image: '',
    abilityBonuses: { str: 2, cha: 1 },
    speed: 30,
    size: 'Средний',
    traits: ['Драконье наследие', 'Дыхательное оружие', 'Сопротивляемость урону'],
  },
  {
    id: 'tiefling',
    name: 'Тифлинг',
    description: 'Потомки инфернальных существ, обладающие врождённой магией и сопротивляемостью огню.',
    image: '',
    abilityBonuses: { int: 1, cha: 2 },
    speed: 30,
    size: 'Средний',
    traits: ['Тёмное зрение', 'Адская сопротивляемость', 'Инфернальное наследие'],
  },
];

export const BACKGROUNDS: Background[] = [
  {
    id: 'artist',
    name: 'Артист',
    description:
      'Вы зарабатывали на жизнь выступлениями — музыкой, танцами, акробатикой или театром. Вы привыкли к публике и легко привлекаете внимание.',
    image: '',
    skillProficiencies: ['Акробатика', 'Выступление'],
    toolProficiencies: ['Набор для грима', '1 музыкальный инструмент'],
    feature: 'Популярность',
  },
  {
    id: 'folk-hero',
    name: 'Народный герой',
    description:
      'Вы простой человек, совершивший поступок, который сделал вас героем среди простого народа.',
    image: '',
    skillProficiencies: ['Уход за животными', 'Выживание'],
    toolProficiencies: ['Набор ремесленника', 'транспорт'],
    feature: 'Поддержка простых людей',
  },
  {
    id: 'sage',
    name: 'Мудрец',
    description:
      'Вы посвятили жизнь изучению знаний — магии, истории или науки. Вас движет жажда открытий и понимания мира.',
    image: '',
    skillProficiencies: ['Магия', 'История'],
    toolProficiencies: [],
    feature: 'Исследователь',
  },
  {
    id: 'sailor',
    name: 'Моряк',
    description:
      'Вы провели годы в море, служа на корабле и переживая штормы и битвы. Вы хорошо знаете жизнь портов и морские традиции.',
    image: '',
    skillProficiencies: ['Атлетика', 'Восприятие'],
    toolProficiencies: ['Навигационные инструменты', 'транспорт (водный)'],
    feature: 'Морской переход',
  },
  {
    id: 'hermit',
    name: 'Отшельник',
    description:
      'Вы долгое время жили в уединении, вдали от цивилизации. В одиночестве вы пришли к важному открытию или прозрению.',
    image: '',
    skillProficiencies: ['Медицина', 'Религия'],
    toolProficiencies: ['Набор травника'],
    feature: 'Открытие',
  },
  {
    id: 'charlatan',
    name: 'Шарлатан',
    description:
      'Вы зарабатывали обманом, притворяясь тем, кем не являетесь. Ложные личности и фальшивые истории — ваши инструменты.',
    image: '',
    skillProficiencies: ['Обман', 'Ловкость рук'],
    toolProficiencies: ['Набор для маскировки', 'набор для подделки документов'],
    feature: 'Ложная личность',
  },
  {
    id: 'soldier',
    name: 'Солдат',
    description:
      'Вы служили в армии и участвовали в военных кампаниях. Вы знакомы с дисциплиной, иерархией и военной жизнью.',
    image: '',
    skillProficiencies: ['Атлетика', 'Запугивание'],
    toolProficiencies: ['Набор для азартных игр', 'транспорт (наземный)'],
    feature: 'Воинское звание',
  },
  {
    id: 'guild-artisan',
    name: 'Ремесленник гильдии',
    description:
      'Вы состояли в гильдии мастеров и освоили определённое ремесло. У вас есть профессиональные связи и деловая репутация.',
    image: '',
    skillProficiencies: ['Проницательность', 'Убеждение'],
    toolProficiencies: ['Инструменты ремесла'],
    feature: 'Членство в гильдии',
  },
  {
    id: 'acolyte',
    name: 'Аколит',
    description:
      'Вы служили в храме и посвятили себя религиозным обязанностям. У вас есть связь с духовенством и религиозным сообществом.',
    image: '',
    skillProficiencies: ['Проницательность', 'Религия'],
    toolProficiencies: [],
    feature: 'Приют храма',
  },
  {
    id: 'criminal',
    name: 'Преступник',
    description:
      'Вы жили вне закона, занимаясь кражами, мошенничеством или другими тёмными делами. У вас есть связи в преступном мире.',
    image: '',
    skillProficiencies: ['Обман', 'Скрытность'],
    toolProficiencies: ['Воровские инструменты', 'набор для азартных игр'],
    feature: 'Связь с криминалом',
  },
  {
    id: 'noble',
    name: 'Благородный',
    description:
      'Вы родились или были приняты в аристократическую семью. Вы привыкли к привилегиям, статусу и влиянию.',
    image: '',
    skillProficiencies: ['История', 'Убеждение'],
    toolProficiencies: ['Набор для азартных игр'],
    feature: 'Привилегии знати',
  },
  {
    id: 'outlander',
    name: 'Чужеземец',
    description:
      'Вы выросли вдали от городов, в дикой местности или среди кочевников. Вы привыкли полагаться на себя и природу.',
    image: '',
    skillProficiencies: ['Атлетика', 'Выживание'],
    toolProficiencies: ['1 музыкальный инструмент'],
    feature: 'Странник',
  },
];

export const SKILLS: Skill[] = [
  { id: 'acrobatics', name: 'Акробатика', ability: 'dex', description: 'Баланс и гибкость' },
  {
    id: 'animal-handling',
    name: 'Уход за животными',
    ability: 'wis',
    description: 'Работа с животными',
  },
  { id: 'arcana', name: 'Магия', ability: 'int', description: 'Знания о магии' },
  { id: 'athletics', name: 'Атлетика', ability: 'str', description: 'Физическая мощь' },
  { id: 'deception', name: 'Обман', ability: 'cha', description: 'Ложь' },
  { id: 'history', name: 'История', ability: 'int', description: 'Знание прошлого' },
  { id: 'insight', name: 'Проницательность', ability: 'wis', description: 'Чтение людей' },
  { id: 'intimidation', name: 'Запугивание', ability: 'cha', description: 'Давление страхом' },
  {
    id: 'investigation',
    name: 'Анализ',
    ability: 'int',
    description: 'Поиск улик',
  },
  { id: 'medicine', name: 'Медицина', ability: 'wis', description: 'Первая помощь' },
  { id: 'nature', name: 'Природа', ability: 'int', description: 'Знания о природе' },
  { id: 'perception', name: 'Восприятие', ability: 'wis', description: 'Внимательность' },
  { id: 'performance', name: 'Выступление', ability: 'cha', description: 'Сценическое искусство' },
  { id: 'persuasion', name: 'Убеждение', ability: 'cha', description: 'Дипломатия' },
  { id: 'religion', name: 'Религия', ability: 'int', description: 'Знания о вере' },
  {
    id: 'sleight-of-hand',
    name: 'Ловкость рук',
    ability: 'dex',
    description: 'Мелкая моторика',
  },
  { id: 'stealth', name: 'Скрытность', ability: 'dex', description: 'Незаметность' },
  { id: 'survival', name: 'Выживание', ability: 'wis', description: 'Жизнь в дикой природе' },
];

export const EQUIPMENT_PRESETS: Record<string, EquipmentPreset[]> = {
  barbarian: [
    {
      id: 'barbarian-melee',
      name: 'Ближний боец',
      description: 'Экипировка для ближнего боя с акцентом на урон и выживаемость',
      items: ['Боевой топор', 'Два ручных топора', 'Сумка иследователя', 'Четыре копья'],
    },
    {
      id: 'barbarian-versatile',
      name: 'Versatile Fighter',
      description: 'Mix of melee and ranged options',
      items: ['Длиный меч', 'Короткий лук и 20 стрел', 'Сумка иследователя', 'Два ручных топора'],
    },
  ],
  bard: [
    {
      id: 'bard-diplomat',
      name: 'Дипломат',
      description: 'Экипировка для социальных взаимодействий и легкого боя',
      items: ['Рапира', 'Лютня', 'Легкая броня', 'Набор дипломата', 'Клинок'],
    },
    {
      id: 'bard-entertainer',
      name: 'Артист',
      description: 'Снаряжение для выступлений и универсальное оружие',
      items: ['Длинный меч', 'Лира', 'Кожаный доспех', 'Набор артиста', 'Кинжал'],
    },
  ],
  cleric: [
    {
      id: 'cleric-healer',
      name: 'Целитель',
      description: 'Защитное снаряжение для поддержки',
      items: ['Булава', 'Чешуйчатый доспех', 'Лёгкий арбалет с 20 болтами', 'Набор жреца', 'Щит', 'Священный символ'],
    },
    {
      id: 'cleric-warrior',
      name: 'Боевой жрец',
      description: 'Снаряжение, ориентированное на бой',
      items: ['Боевой молот', 'Кольчужный доспех', 'Щит', 'Набор жреца', 'Священный символ'],
    },
  ],
  druid: [
    {
      id: 'druid-nature',
      name: 'Страж природы',
      description: 'Природное оружие и инструменты',
      items: ['Деревянный щит', 'Скимитар', 'Кожаный доспех', 'Набор исследователя', 'Друидический фокус'],
    },
    {
      id: 'druid-caster',
      name: 'Заклинатель',
      description: 'Упор на магию',
      items: ['Боевой посох', 'Кожаный доспех', 'Набор исследователя', 'Друидический фокус', 'Набор травника'],
    },
  ],
  fighter: [
    {
      id: 'fighter-defender',
      name: 'Защитник',
      description: 'Тяжёлая броня и щит',
      items: ['Длинный меч', 'Щит', 'Кольчужный доспех', 'Лёгкий арбалет с 20 болтами', 'Набор исследователя подземелий'],
    },
    {
      id: 'fighter-striker',
      name: 'Ударник',
      description: 'Двуручное оружие',
      items: ['Двуручный меч', 'Два ручных топора', 'Кольчужный доспех', 'Набор исследователя подземелий'],
    },
  ],
  rogue: [
    {
      id: 'rogue-thief',
      name: 'Вор',
      description: 'Скрытность и взлом',
      items: ['Рапира', 'Короткий лук с 20 стрелами', 'Кожаный доспех', 'Воровские инструменты', 'Набор исследователя подземелий', 'Два кинжала'],
    },
    {
      id: 'rogue-assassin',
      name: 'Убийца',
      description: 'Точечные атаки из тени',
      items: ['Короткий меч', 'Короткий лук с 20 стрелами', 'Кожаный доспех', 'Набор отравителя', 'Набор исследователя подземелий', 'Два кинжала'],
    },
  ],
  wizard: [
    {
      id: 'wizard-scholar',
      name: 'Учёный маг',
      description: 'Книга заклинаний и защита',
      items: ['Боевой посох', 'Книга заклинаний', 'Мешочек с компонентами', 'Набор учёного', 'Кинжал'],
    },
    {
      id: 'wizard-battle',
      name: 'Боевой маг',
      description: 'Магия для сражений',
      items: ['Кинжал', 'Мешочек с компонентами', 'Книга заклинаний', 'Набор исследователя', 'Лёгкий арбалет с 20 болтами'],
    },
  ],
  sorcerer: [
    {
      id: 'sorcerer-elemental',
      name: 'Стихийный чародей',
      description: 'Сила врождённой магии',
      items: ['Лёгкий арбалет с 20 болтами', 'Мешочек с компонентами', 'Набор исследователя', 'Два кинжала'],
    },
    {
      id: 'sorcerer-mystic',
      name: 'Таинственный чародей',
      description: 'Контроль и разрушение',
      items: ['Кинжал', 'Магический фокус', 'Набор учёного', 'Два кинжала'],
    },
  ],
  warlock: [
    {
      id: 'warlock-pactblade',
      name: 'Клинок пакта',
      description: 'Оружие и тёмная магия',
      items: ['Рапира', 'Кожаный доспех', 'Простой арбалет с 20 болтами', 'Мешочек с компонентами', 'Набор учёного', 'Два кинжала'],
    },
    {
      id: 'warlock-occult',
      name: 'Оккультист',
      description: 'Тайные знания',
      items: ['Кинжал', 'Магический фокус', 'Набор учёного', 'Книга заклинаний (гримоар)', 'Два кинжала'],
    },
  ],
  paladin: [
    {
      id: 'paladin-guardian',
      name: 'Страж веры',
      description: 'Щит и священная защита',
      items: ['Длинный меч', 'Щит', 'Кольчужный доспех', 'Набор жреца', 'Священный символ'],
    },
    {
      id: 'paladin-avenger',
      name: 'Каратель',
      description: 'Двуручное оружие и мощь',
      items: ['Двуручный меч', 'Кольчужный доспех', 'Набор жреца', 'Священный символ', 'Пять метательных копий'],
    },
  ],
  ranger: [
    {
      id: 'ranger-archer',
      name: 'Лучник',
      description: 'Дальний бой и выживание',
      items: ['Длинный лук с 20 стрелами', 'Кожаный доспех', 'Два коротких меча', 'Набор исследователя', 'Фокус друида'],
    },
    {
      id: 'ranger-hunter',
      name: 'Охотник',
      description: 'Ближний бой и слежка',
      items: ['Два коротких меча', 'Кожаный доспех', 'Короткий лук с 20 стрелами', 'Набор исследователя', 'Фокус друида'],
    },
  ],
  monk: [
    {
      id: 'monk-ascetic',
      name: 'Аскет',
      description: 'Боевые искусства',
      items: ['Боевой посох', 'Дротики (10)', 'Набор исследователя', 'Верёвка 50 фт'],
    },
    {
      id: 'monk-shadow',
      name: 'Теневой монах',
      description: 'Скрытность и скорость',
      items: ['Короткий меч', 'Дротики (10)', 'Набор исследователя подземелий', 'Верёвка 50 фт'],
    },
  ],

};

export const SPELLS: Record<string, { cantrips: Spell[]; level1: Spell[] }> = {
  // Паладин и следопыт в базовых правилах не имеют заговоров (если не использовать опциональные правила/подклассы)
  paladin: {
    cantrips: [],
    level1: [
      {
        id: 'bless',
        name: 'Благословение',
        level: 1,
        school: 'Очарование',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Благословляете союзников, давая бонус к атакам и спасброскам.',
      },
      {
        id: 'cure-wounds',
        name: 'Лечение ран',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Исцеляете существо прикосновением.',
      },
      {
        id: 'shield-of-faith',
        name: 'Щит веры',
        level: 1,
        school: 'Ограждение',
        castingTime: '1 бонусное действие',
        range: '60 футов',
        description: 'Даёте существу +2 к КД на время действия.',
      },
      {
        id: 'wrathful-smite',
        name: 'Гневная кара',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 бонусное действие',
        range: 'На себя',
        description: 'Следующий удар оружием усиливается и может напугать цель.',
      },
    ],
  },

  ranger: {
    cantrips: [],
    level1: [
      {
        id: 'hunters-mark',
        name: 'Метка охотника',
        level: 1,
        school: 'Прорицание',
        castingTime: '1 бонусное действие',
        range: '90 футов',
        description: 'Помечаете цель и наносите ей дополнительный урон оружием.',
      },
      {
        id: 'cure-wounds',
        name: 'Лечение ран',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Исцеляете существо прикосновением.',
      },
      {
        id: 'goodberry',
        name: 'Хорошая ягода',
        level: 1,
        school: 'Преобразование',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Создаёте ягоды, которые лечат и питают.',
      },
      {
        id: 'ensnaring-strike',
        name: 'Опутывающий удар',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 бонусное действие',
        range: 'На себя',
        description: 'Следующая атака оружием может опутать цель лозами.',
      },
    ],
  },

  bard: {
    cantrips: [
      {
        id: 'vicious-mockery',
        name: 'Злобная насмешка',
        level: 0,
        school: 'Очарование',
        castingTime: '1 действие',
        range: '60 футов',
        description: 'Оскорбляете существо: психический урон и помеха на следующую атаку.',
      },
      {
        id: 'minor-illusion',
        name: 'Малая иллюзия',
        level: 0,
        school: 'Иллюзия',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Создаёте звук или изображение предмета.',
      },
      {
        id: 'prestidigitation',
        name: 'Фокусы',
        level: 0,
        school: 'Преобразование',
        castingTime: '1 действие',
        range: '10 футов',
        description: 'Небольшие магические трюки и эффекты.',
      },
      {
        id: 'mage-hand',
        name: 'Волшебная рука',
        level: 0,
        school: 'Вызов',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Создаёте призрачную руку для манипуляции предметами.',
      },
    ],
    level1: [
      {
        id: 'healing-word',
        name: 'Лечащее слово',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 бонусное действие',
        range: '60 футов',
        description: 'Исцеляете существо словом.',
      },
      {
        id: 'thunderwave',
        name: 'Громовая волна',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: 'На себя (куб 15 футов)',
        description: 'Удар грома отталкивает существ и наносит урон.',
      },
      {
        id: 'charm-person',
        name: 'Очаровать человека',
        level: 1,
        school: 'Очарование',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Очаровываете гуманоида, делая его дружелюбнее.',
      },
      {
        id: 'disguise-self',
        name: 'Маскировка',
        level: 1,
        school: 'Иллюзия',
        castingTime: '1 действие',
        range: 'На себя',
        description: 'Меняете внешность иллюзией.',
      },
    ],
  },

  cleric: {
    cantrips: [
      {
        id: 'sacred-flame',
        name: 'Священное пламя',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '60 футов',
        description: 'Поражаете существо сияющим пламенем.',
      },
      {
        id: 'spare-the-dying',
        name: 'Пощадить умирающего',
        level: 0,
        school: 'Некромантия',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Стабилизируете умирающее существо.',
      },
      {
        id: 'light',
        name: 'Свет',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Заставляете предмет излучать свет.',
      },
      {
        id: 'guidance',
        name: 'Наставление',
        level: 0,
        school: 'Прорицание',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Даёте бонус к одной проверке характеристики.',
      },
    ],
    level1: [
      {
        id: 'cure-wounds',
        name: 'Лечение ран',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Исцеляете существо прикосновением.',
      },
      {
        id: 'bless',
        name: 'Благословение',
        level: 1,
        school: 'Очарование',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Благословляете союзников, давая бонус к атакам и спасброскам.',
      },
      {
        id: 'shield-of-faith',
        name: 'Щит веры',
        level: 1,
        school: 'Ограждение',
        castingTime: '1 бонусное действие',
        range: '60 футов',
        description: 'Даёте существу +2 к КД на время действия.',
      },
      {
        id: 'guiding-bolt',
        name: 'Направляющий снаряд',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '120 футов',
        description: 'Сияющая энергия бьёт цель и даёт преимущество следующей атаке по ней.',
      },
    ],
  },

  druid: {
    cantrips: [
      {
        id: 'produce-flame',
        name: 'Создание пламени',
        level: 0,
        school: 'Вызов',
        castingTime: '1 действие',
        range: 'На себя',
        description: 'Создаёте пламя для света или атаки.',
      },
      {
        id: 'shillelagh',
        name: 'Шиллела',
        level: 0,
        school: 'Преобразование',
        castingTime: '1 бонусное действие',
        range: 'Касание',
        description: 'Наполняете дубинку/посох магией.',
      },
      {
        id: 'druidcraft',
        name: 'Друидизм',
        level: 0,
        school: 'Преобразование',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Небольшие природные эффекты и предзнаменования.',
      },
      {
        id: 'thorn-whip',
        name: 'Кнут из шипов',
        level: 0,
        school: 'Преобразование',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Шипастые лозы бьют и притягивают цель ближе.',
      },
    ],
    level1: [
      {
        id: 'entangle',
        name: 'Опутывание',
        level: 1,
        school: 'Вызов',
        castingTime: '1 действие',
        range: '90 футов',
        description: 'Лозы хватают существ и могут их опутать.',
      },
      {
        id: 'goodberry',
        name: 'Хорошая ягода',
        level: 1,
        school: 'Преобразование',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Создаёте ягоды, которые лечат и питают.',
      },
      {
        id: 'faerie-fire',
        name: 'Огни фей',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '60 футов',
        description: 'Подсвечиваете существ: атаки по ним получают преимущество.',
      },
      {
        id: 'speak-with-animals',
        name: 'Разговор с животными',
        level: 1,
        school: 'Прорицание',
        castingTime: '1 действие',
        range: 'На себя',
        description: 'Можете общаться с животными.',
      },
    ],
  },

  sorcerer: {
    cantrips: [
      {
        id: 'fire-bolt',
        name: 'Огненный снаряд',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '120 футов',
        description: 'Метаете огненный снаряд, нанося урон огнём.',
      },
      {
        id: 'ray-of-frost',
        name: 'Луч холода',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '60 футов',
        description: 'Холодный луч наносит урон и замедляет цель.',
      },
      {
        id: 'shocking-grasp',
        name: 'Электрошок',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Молния бьёт цель вблизи, мешая ей реагировать.',
      },
      {
        id: 'mage-hand',
        name: 'Волшебная рука',
        level: 0,
        school: 'Вызов',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Создаёте призрачную руку для манипуляции предметами.',
      },
    ],
    level1: [
      {
        id: 'magic-missile',
        name: 'Волшебная стрела',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '120 футов',
        description: 'Создаёте самонаводящиеся магические стрелы.',
      },
      {
        id: 'shield',
        name: 'Щит',
        level: 1,
        school: 'Ограждение',
        castingTime: '1 реакция',
        range: 'На себя',
        description: 'Магический щит резко повышает КД на короткое время.',
      },
      {
        id: 'burning-hands',
        name: 'Пылающие руки',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: 'На себя (конус 15 футов)',
        description: 'Конус огня обжигает существ перед вами.',
      },
      {
        id: 'chromatic-orb',
        name: 'Хроматическая сфера',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '90 футов',
        description: 'Сфера выбранной стихии наносит соответствующий урон.',
      },
    ],
  },

  warlock: {
    cantrips: [
      {
        id: 'eldritch-blast',
        name: 'Мистический заряд',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '120 футов',
        description: 'Стреляете лучом мистической энергии.',
      },
      {
        id: 'chill-touch',
        name: 'Ледяное прикосновение',
        level: 0,
        school: 'Некромантия',
        castingTime: '1 действие',
        range: '120 футов',
        description: 'Призрачная рука наносит некротический урон и мешает лечению.',
      },
      {
        id: 'mage-hand',
        name: 'Волшебная рука',
        level: 0,
        school: 'Вызов',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Создаёте призрачную руку для манипуляции предметами.',
      },
      {
        id: 'minor-illusion',
        name: 'Малая иллюзия',
        level: 0,
        school: 'Иллюзия',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Создаёте звук или изображение предмета.',
      },
    ],
    level1: [
      {
        id: 'hex',
        name: 'Порча',
        level: 1,
        school: 'Очарование',
        castingTime: '1 бонусное действие',
        range: '90 футов',
        description: 'Проклинаете цель: доп. урон и помеха на выбранные проверки.',
      },
      {
        id: 'arms-of-hadar',
        name: 'Руки Хадара',
        level: 1,
        school: 'Вызов',
        castingTime: '1 действие',
        range: 'На себя (радиус 10 футов)',
        description: 'Тёмные щупальца бьют рядом стоящих существ.',
      },
      {
        id: 'hellish-rebuke',
        name: 'Адское возмездие',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 реакция',
        range: '60 футов',
        description: 'Когда вас ранят, вы отвечаете вспышкой адского пламени.',
      },
      {
        id: 'armor-of-agathys',
        name: 'Доспех Агатиса',
        level: 1,
        school: 'Ограждение',
        castingTime: '1 действие',
        range: 'На себя',
        description: 'Получаете временные хиты; атакующие вблизи получают урон холодом.',
      },
    ],
  },

  wizard: {
    cantrips: [
      {
        id: 'fire-bolt',
        name: 'Огненный снаряд',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '120 футов',
        description: 'Метаете огненный снаряд, нанося урон огнём.',
      },
      {
        id: 'ray-of-frost',
        name: 'Луч холода',
        level: 0,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '60 футов',
        description: 'Холодный луч наносит урон и замедляет цель.',
      },
      {
        id: 'mage-hand',
        name: 'Волшебная рука',
        level: 0,
        school: 'Вызов',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Создаёте призрачную руку для манипуляции предметами.',
      },
      {
        id: 'minor-illusion',
        name: 'Малая иллюзия',
        level: 0,
        school: 'Иллюзия',
        castingTime: '1 действие',
        range: '30 футов',
        description: 'Создаёте звук или изображение предмета.',
      },
    ],
    level1: [
      {
        id: 'magic-missile',
        name: 'Волшебная стрела',
        level: 1,
        school: 'Воплощение',
        castingTime: '1 действие',
        range: '120 футов',
        description: 'Создаёте самонаводящиеся магические стрелы.',
      },
      {
        id: 'shield',
        name: 'Щит',
        level: 1,
        school: 'Ограждение',
        castingTime: '1 реакция',
        range: 'На себя',
        description: 'Магический щит резко повышает КД на короткое время.',
      },
      {
        id: 'mage-armor',
        name: 'Магическая броня',
        level: 1,
        school: 'Ограждение',
        castingTime: '1 действие',
        range: 'Касание',
        description: 'Даёте существу базовую защиту без доспеха.',
      },
      {
        id: 'sleep',
        name: 'Сон',
        level: 1,
        school: 'Очарование',
        castingTime: '1 действие',
        range: '90 футов',
        description: 'Погружаете существ в магический сон (по сумме хитов).',
      },
    ],
  },
};


// Helper function to get class by ID
export function getClassById(classId: string): CharacterClass | undefined {
  return CHARACTER_CLASSES.find((c) => c.id === classId);
}

// Helper function to get race by ID
export function getRaceById(raceId: string): Race | undefined {
  return RACES.find((r) => r.id === raceId);
}

// Helper function to get background by ID
export function getBackgroundById(backgroundId: string): Background | undefined {
  return BACKGROUNDS.find((b) => b.id === backgroundId);
}

// Helper function to check if class is caster
export function isClassCaster(classId: string): boolean {
  const characterClass = getClassById(classId);
  return characterClass?.isCaster ?? false;
}
